export const UNREAL_REG_PAYLOAD_CONFIG = {
  UNREAL_OPENAI_ADDRESS: process.env.NEXT_PUBLIC_UNREAL_OPENAI_ADDRESS!,
  CALLS_INITIAL: Number(process.env.NEXT_PUBLIC_UNREAL_CALLS_INITIAL) || 100,
  EXPIRY_SECONDS: Number(process.env.NEXT_PUBLIC_UNREAL_EXPIRY_SECONDS) || 3600,
};

export const unrealApiUrl = process.env.UNREAL_API_URL!;
