export const models = [
  {
    id: "deepseek-r1",
    created: 1737397673,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "deepseek-r1-0528",
    created: 1748456377,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "deepseek-r1-basic",
    created: 1742306746,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "deepseek-v3",
    created: 1735576668,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "deepseek-v3-0324",
    created: 1742827220,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "deepseek-v3p1",
    created: 1755758988,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "deepseek-v3p1-terminus",
    created: 1758586241,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 163840,
    modalities: ["text"],
  },
  {
    id: "glm-4p5",
    created: 1753809636,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "glm-4p5-air",
    created: 1754089426,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "gpt-oss-120b",
    created: 1754345600,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "gpt-oss-20b",
    created: 1754345466,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "kimi-k2-instruct",
    created: 1752259096,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "kimi-k2-instruct-0905",
    created: 1757018994,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "llama-v3p1-405b-instruct",
    created: 1721428386,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "llama-v3p1-70b-instruct",
    created: 1721287357,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "llama-v3p1-8b-instruct",
    created: 1721692808,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "llama-v3p3-70b-instruct",
    created: 1733442103,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "llama4-maverick-instruct-basic",
    created: 1743878495,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: true,
    supports_tools: true,
    context_length: 1048576,
    modalities: ["text"],
  },
  {
    id: "llama4-scout-instruct-basic",
    created: 1743878279,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: true,
    supports_tools: true,
    context_length: 1048576,
    modalities: ["text"],
  },
  {
    id: "mixtral-8x22b-instruct",
    created: 1713375508,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 65536,
    modalities: ["text"],
  },
  {
    id: "qwen2p5-vl-32b-instruct",
    created: 1743392739,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: true,
    supports_tools: false,
    context_length: 128000,
    modalities: ["text", "image"],
  },
  {
    id: "qwen3-235b-a22b",
    created: 1745885249,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    created: 1753124424,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "qwen3-235b-a22b-thinking-2507",
    created: 1753455434,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "qwen3-30b-a3b",
    created: 1745878133,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "qwen3-30b-a3b-instruct-2507",
    created: 1753808388,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "qwen3-30b-a3b-thinking-2507",
    created: 1753916446,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    modalities: ["text"],
  },
  {
    id: "qwen3-coder-30b-a3b-instruct",
    created: 1754063588,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    created: 1753211090,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: true,
    context_length: 262144,
    modalities: ["text"],
  },
  {
    id: "qwen3-embedding-8b",
    created: 1755707090,
    object: "model",
    owned_by: "fireworks",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 40960,
    modalities: ["text"],
  },
  {
    id: "dobby-mini-unhinged-plus-llama-3-1-8b",
    created: 1748467427,
    object: "model",
    owned_by: "sentientfoundation-serverless",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "dobby-unhinged-llama-3-3-70b-new",
    created: 1739563474,
    object: "model",
    owned_by: "sentientfoundation",
    kind: "HF_BASE_MODEL",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    context_length: 131072,
    modalities: ["text"],
  },
  {
    id: "debatecards-70b-ft-3epoch-dpo-v2",
    created: 1743381121,
    object: "model",
    owned_by: "tvergho-87e44d",
    kind: "HF_PEFT_ADDON",
    supports_chat: true,
    supports_image_input: false,
    supports_tools: false,
    modalities: ["text"],
  },
];
